Keycloak api key generation provider
PhilanthropyDataCommons/auth pull request #1
Opened 2022-10-28 14:16 UTC by gmurtaza00

# Keycloak custom provider
- This provider creates a unique key upon user registration and set that key as a user-attribute namely api-key.
- The user can login to his account and see the api-key.
- This api-key will be sent by user in header _('x-api-key')_ to access protected routes of the api-key.
- This provider also creates a custom route to verify the api-key
   http://localhost:8080/realms/realm_name/check?apiKey={api-key}

2022-10-29 20:44 UTC, slifty reviewed
This is NOT a full review but wanted to post since I have to go AFK -- main question is whether we can add a linter for Java (does such a thing exist?)

2022-11-01 16:05 UTC, bickelj commented on api-key-module/pom.xml
> +    <groupId>com.pdc</groupId>
This probably should be either `org.pdc` or `org.philanthropydatacommons` and likewise throughout.

2022-11-01 16:14 UTC, bickelj commented on README.md
> +https://docs.google.com/document/d/1aawlITZu_6xAcVetyqvE7NrETay7eAOhVXwfnJcwC7A/edit?usp=sharing
This document helps me see how to get started locally with a keycloak instance, but I am thinking about how to get this same setup programmatically using a bitnami keycloak image without exposing the keycloak interfaces to the world.

2022-11-01 16:22 UTC, bickelj commented on README.md
> +https://docs.google.com/document/d/1aawlITZu_6xAcVetyqvE7NrETay7eAOhVXwfnJcwC7A/edit?usp=sharing
I guess we would expose the keycloak service, right? That way folks can register, regenerate api keys, etc.?

2022-11-01 16:27 UTC, bickelj commented on README.md
> +```mvn -f api-key-module package```
I was able to run this successfully locally within this branch.

2022-11-01 16:44 UTC, bickelj commented on api-key-module/src/main/java/com/pdc/providers/ApiKeyResourceProviderFactory.java
> +
Checkstyle comes with a googly configuration:
```
$ dpkg -L checkstyle
/.
/usr
/usr/bin
/usr/bin/checkstyle
/usr/share
/usr/share/checkstyle
/usr/share/checkstyle/google_checks.xml
```
E.g.
```
keycloak-extensions/api-key-module$ checkstyle -c /usr/share/checkstyle/google_checks.xml src/main/java/com/pdc/providers/*.java
Starting audit...
[WARN] keycloak-extensions/api-key-module/src/main/java/com/pdc/providers/ApiKeyResourceProviderFactory.java:12: 'method def modifier' has incorrect indentation level 4, expected level should be 2. [Indentation]
[WARN] keycloak-extensions/api-key-module/src/main/java/com/pdc/providers/ApiKeyResourceProviderFactory.java:13: 'method def' child has incorrect indentation level 8, expected level should be 4. [Indentation]
```

2022-11-01 21:16 UTC, slifty commented on api-key-module/pom.xml
> +    <groupId>com.pdc</groupId>
FWIW I vote for the more descriptive one (also matches the URL)

2022-11-02 12:35 UTC, gmurtaza00 commented on README.md
> +https://docs.google.com/document/d/1aawlITZu_6xAcVetyqvE7NrETay7eAOhVXwfnJcwC7A/edit?usp=sharing
Yeah we will have to expose keycloak service for the purpose of login and register.

2022-11-02 16:52 UTC, bickelj requested changes
This is good for the module/jar name but then there are also the package statements in each class at the top, the directory structure leading to those too.

2022-11-03 18:21 UTC, bickelj approved these changes
I do not yet know enough about keycloak or JWT to know the implications of including this jar, but I see that you made the requested changes and this should be merged.

2023-02-24 19:22 UTC, jasonaowen commented
Is this PR still relevant? It seems like it may have been written before the plan for OAuth tokens was adopted; is that accurate?

2023-02-24 20:00 UTC, bickelj commented
@jasonaowen I would say it is superceded by the use of OAuth 2 / OIDC JWTs, yes.

Looking back at my objections to this API key extension approach, namely the "internal SPI" and "extending keycloak" objections in https://github.com/PhilanthropyDataCommons/service/issues/96#issuecomment-1307619151 the same "internal SPI" warning occurs with PR #3 and it too is an extension to keycloak. I think I am still uneasy with the API key extension, though. The approach in this PR was to add a secret API key to a keycloak user's attributes and then let passing that value be the authentication (or bypass authentication). We implemented a simple version of this without keycloak in the app instead.

2023-02-24 20:01 UTC, bickelj commented
@slifty @gmurtaza00 @reefdog If any of y'all think this should be resurrected, please re-open.

2023-02-24 20:01 UTC, closed without merging

2023-02-24 20:02 UTC, jasonaowen commented
Thank you for the history, @bickelj! It is very helpful.