Afford a twilio SMS Authenticator for keycloak
PhilanthropyDataCommons/auth pull request #3
Opened 2023-02-23 01:19 UTC by bickelj

This project creates a `lib-all.jar` that can be placed in keycloak's directory named `/providers`. When present, the jar affords an SMS authenticator. The Authenticator implementation is based on dasniko's at https://github.com/dasniko/keycloak-2fa-sms-authenticator and also requires his keycloak-requiredaction jar to be in `/providers`. After the jars are in place, keycloak needs to be configured to use them. See https://www.n-k.de/2020/12/keycloak-2fa-sms-authentication.html and
https://github.com/PhilanthropyDataCommons/auth/issues/2#issuecomment-1440797906 for more details.

The twilio settings are loaded via environment variables:
 - `TWILIO_PHONE_NUMBER`: the "from" phone number set up in twilio.
 - `TWILIO_ACCOUNT_SID`: the SID or username for twilio API access.
 - `TWILIO_AUTH_TOKEN`: the token or secret for twilio API access.

2023-02-23 15:23 UTC, bickelj reviewed
This PR is a little hasty in the sense that it is missing a README and some of the comments I just made need to be incorporated as comments in the code. There are also recommendations in the comments by dasniko that should be followed. The reason to push code is it is good to push frequently and to show progress, affording the opportunity for specific feedback.

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/gradle/wrapper/gradle-wrapper.properties
> +distributionBase=GRADLE_USER_HOME
This properties file, the above binary, and below `gradlew` scripts are boilerplate/bootstrapping for the gradle build system. Yes, it is customary to commit the `gradle-wrapper.jar` binary to the repository but no other jars. The reason it is here is to make it easy to run gradle commands, e.g. `../gradlew test` just works.

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    id("com.github.johnrengelman.shadow") version "7.1.2"
The reason to use this is to include the twilio library and (some of) its dependencies into the provider library jar, simplifying the delivery.

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    compileOnly("org.keycloak:keycloak-core:20.0.3")
`compileOnly` means "we need this and its dependencies only at compile time, don't include it at runtime." This is because the keycloak classpath already has these keycloak libraries and we are adding our provider to the keycloak classpath.

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    implementation("com.twilio.sdk:twilio:9.2.3")
`implementation` means we use this and intend for it to be included at runtime but don't intend to expose it for consumers to use (unless they also wish to explicitly include it, which they should if they depend on it). Some of the downstream dependencies are already downstream dependencies of keycloak jars and are already on the keycloak classpath. See below.

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +        exclude(dependency("org.slf4j:.*:.*"))
The above are already on the classpath in keycloak 20.0.2, so there is some danger of brittleness in excluding them from the shadow jar (less danger than duplicating them in the shadow jar).

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/Sms.java
> +        Twilio.init(System.getenv("TWILIO_ACCOUNT_SID"), System.getenv("TWILIO_AUTH_TOKEN"));
For better testability these might be converted to Java System Properties rather than env vars. But env vars are simple enough and the code is so little...

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +    private static final org.jboss.logging.Logger JBOSS_LOGGER = org.jboss.logging.Logger.getLogger(SmsAuthenticator.class + ".jboss");
Oops, I meant to remove this logger.

2023-02-23 15:23 UTC, bickelj commented on twilio-keycloak-provider/settings.gradle.kts
> +include("lib")
The `lib` name is kind of awkward.

2023-02-24 08:36 UTC, jasonaowen requested changes
Thanks for working on this, @bickelj! This looks very promising.

I don't have a full environment set up yet, and I don't have access to any Twilio credentials, so I haven't been able to test this yet - at this point I'm only looking at the code.

I think it would make sense to squash the four commits down into one - I think this is just one logical change, right?

Sorry for so many comments; they're not all equally important! I hope this is helpful feedback.

2023-02-24 08:36 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        boolean isValid = enteredCode.equals(code);
I believe this is vulnerable to a [timing attack](https://codahale.com/a-lesson-in-timing-attacks/): `String#equals` will do a character-by-character comparison, and return on the first inequality; the time it takes to do so can reveal information to an attacker about the correct value.

It may be the case (and I hope it is) that Keycloak has built in defenses against brute force attacks, but in the interest of defense-in-depth, we should use a constant time comparison: [`MessageDigest#isEqual`](https://docs.oracle.com/javase/8/docs/api/java/security/MessageDigest.html#isEqual-byte:A-byte:A-)

```suggestion
        boolean isValid = MessageDigest.isEqual(
            code.getBytes(StandardCharsets.UTF_8),
            enteredCode.getBytes(StandardCharsets.UTF_8)
        );
```

I'd also suggest doing the expiration time check before the code check, both because it is cheaper and to reveal as little to an attacker as possible.

2023-02-24 08:36 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/resources/theme-resources/messages/messages_en.properties
> +smsAuthCodeInvalid=Invalid code entered, please enter it again.
Can we add a trailing newline here, please?

2023-02-24 08:36 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/resources/theme-resources/templates/login-sms.ftl
> +					<input class="${properties.kcButtonClass!} ${properties.kcButtonPrimaryClass!} ${properties.kcButtonBlockClass!} ${properties.kcButtonLargeClass!}" type="submit" value="${msg("doSubmit")}"/>
This is a very long line! Not much to be done for the `class`, but as a whole I find it more readable if we spill it across multiple lines:

```suggestion
					<input
						class="${properties.kcButtonClass!} ${properties.kcButtonPrimaryClass!} ${properties.kcButtonBlockClass!} ${properties.kcButtonLargeClass!}"
						type="submit"
						value="${msg("doSubmit")}"
					/>
```

2023-02-24 08:36 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticatorFactory.java
> +                new ProviderConfigProperty("simulation", "Simulation mode", "In simulation mode, the SMS won't be sent, but printed to the server logs", ProviderConfigProperty.BOOLEAN_TYPE, true)
Are these properties used?

2023-02-24 15:33 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    compileOnly("org.keycloak:keycloak-services:20.0.3")
If it doesn't work with keycloak 21, that would be a red flag. I'll upgrade and see. Good call on the constant, assuming all the library versions are in lockstep. It appears so.

2023-02-24 15:34 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/Sms.java
> +                .create();
Yes. Now that I look at it, probably more, i.e. check message status.

2023-02-24 15:35 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        // mobileNumber of course has to be further validated on proper format, country code, ...
It is something yet to be resolved, yes. It would be nice to validate this earlier, e.g. on form entry in keycloak, but I suppose there are many ways to enter it and therefore it is still good to validate at this point.

2023-02-24 15:37 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +            Sms sms = new Sms();
I like this idea because it also would hoist any `Twilio.init` exceptions to keycloak startup time rather than message send time.

2023-02-24 20:16 UTC, jasonaowen commented
In https://github.com/PhilanthropyDataCommons/auth/pull/1#issuecomment-1444373868, @bickelj wrote:

> Looking back at my objections to this API key extension approach, namely the "internal SPI" and "extending keycloak" objections in [PhilanthropyDataCommons/service#96 (comment)](https://github.com/PhilanthropyDataCommons/service/issues/96#issuecomment-1307619151) the same "internal SPI" warning occurs with PR #3 and it too is an extension to keycloak.

I think a critical difference is that this is extending Keycloak in a way that is not visible to applications that authenticate with Keycloak! This work is more in line with the operational task of "how do we make Keycloak work in our organization with our security requirements", and not part of the development task "how do we make an app that works with Keycloak".

tl;dr: this seems like good and worthwhile work! I have no concerns with this approach.

2023-02-24 20:21 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticatorFactory.java
> +                new ProviderConfigProperty("simulation", "Simulation mode", "In simulation mode, the SMS won't be sent, but printed to the server logs", ProviderConfigProperty.BOOLEAN_TYPE, true)
D'oh, maybe not!

2023-02-25 20:36 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/Sms.java
> +        Twilio.init(System.getenv("TWILIO_ACCOUNT_SID"), System.getenv("TWILIO_AUTH_TOKEN"));
Side note on testability, it is weird that the Twilio library requires static init method call at all. Right away I found https://github.com/twilio/twilio-java/issues/650.

2023-02-26 00:25 UTC, bickelj commented on twilio-keycloak-provider/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip
Done.

2023-02-26 00:27 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    compileOnly("org.keycloak:keycloak-services:20.0.3")
I have yet to try running under keycloak 21, but I can confirm that a problem (`MethodNotFoundError` or some such) occurred when building this library against (current) keycloak `21.0.0` but then running in (old) keycloak `20.0.2`. That is less concerning than if the reverse were true, which I still need to test.

2023-02-26 00:28 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/Sms.java
> +                .create();
Done and done.

2023-02-26 00:33 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        // mobileNumber of course has to be further validated on proper format, country code, ...
I have yet to resolve this but found that Twilio has a [separate API for phone number validation](https://www.twilio.com/docs/lookup/v2-api). I don't think a separate web request would make sense at this point merely to validate the number because we would be no worse off simply attempting the send and getting an error. If there is an existing library that can validate here that is good.

The time to validate would be on entry. For the pilot, I believe we (whoever is administering the keycloak instance) will enter the phone number. Since it's an attribute on a user, it might be rather difficult to enforce validation at create or update. Maybe there is some keycloaky way to do that. But for now, I think it's not as important to worry about that. If we get to the point of users entering their own numbers, then I think it would be worthwhile to make that Twilio validation request at that entry time.

2023-02-26 00:40 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        boolean isValid = enteredCode.equals(code);
I need to still apply this change, but it is probably worthwhile to report this issue upstream because here it is: https://github.com/dasniko/keycloak-2fa-sms-authenticator/blob/6e5765bbf740afad5df0d48ddf8302cfb0e0f4a0/src/main/java/dasniko/keycloak/authenticator/SmsAuthenticator.java#L73

2023-02-26 00:45 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +            Sms sms = new Sms();
Resolved. An interesting thing happens now. Keycloak startup is not when the `SmsAuthenticator` and therefore `SmsSender` (formerly `Sms`) get constructed. That is merely service registration/discovery, I suppose. It is when someone attempts login that construction of the classes occurs and that is when the error now happens. The change is still an improvement and pulling the error back in the right direction, though.

2023-02-27 23:09 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/Sms.java
> +        Twilio.init(System.getenv("TWILIO_ACCOUNT_SID"), System.getenv("TWILIO_AUTH_TOKEN"));
I made the environment variable loading a little more resilient. Do you think it would be much better as `ProviderConfigProperty`? The environment variables are disconnected from keycloak but are pretty straightforward to configure. The `ProviderConfigProperty` values have working defaults but I doubt we can make working defaults with Twilio. The benefit of going to `ProviderConfigProperty` seems to be more seamless integration. I am up for either but inertia kept the env vars.

2023-02-27 23:14 UTC, bickelj commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    compileOnly("org.keycloak:keycloak-services:20.0.3")
The image configured in our [deployment script](https://github.com/PhilanthropyDataCommons/deploy/blob/70638519f5377d374b28a98c60ad3ff6a266cffe/compose.yml#L72) uses bitnami. The reason is bitnami produces exact immutable versions of images (rather than the common practice of updating an image in place),   there are some easier integrations between bitnami images, and they use debian which is familiar to most of us. As of this moment, the [latest image](https://hub.docker.com/layers/bitnami/keycloak/20.0.5-debian-11-r3/images/sha256-014ed030da239b4fda81015f1e5021227184fce342989a073a2c251c5df093df?context=explore) has keycloak 20.0.5. I develop using a similar compose script. So once that team produces a version 21 I will give it a shot.

2023-02-27 23:17 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +            String smsText = String.format(smsAuthText, code, Math.floorDiv(ttl, 60));
Another great suggestion. While doing this I found the overloaded use of the word "ttl" annoying, as well as the frequent date math. So I disambiguated "ttl" from "epoch datetime in millis" and used `java.time` instead.

2023-02-27 23:18 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        boolean isValid = enteredCode.equals(code);
I applied both changes. Thanks for finding this!

2023-02-27 23:20 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticatorFactory.java
> +                new ProviderConfigProperty("simulation", "Simulation mode", "In simulation mode, the SMS won't be sent, but printed to the server logs", ProviderConfigProperty.BOOLEAN_TYPE, true)
I didn't quickly find a parameter in Twilio's API to use senderId, so I included it in the message. I think the simulation mode unnecessarily complicated things so I removed it.

2023-02-27 23:22 UTC, bickelj commented
I plan to squash the commits once the changes are up to snuff. Does that sound reasonable?

2023-02-28 02:05 UTC, jasonaowen commented
> I plan to squash the commits once the changes are up to snuff. Does that sound reasonable?

Of course! I thought that might be the case, but explicit is better than implicit. :)

2023-02-28 02:09 UTC, jasonaowen commented on twilio-keycloak-provider/lib/build.gradle.kts
> +    compileOnly("org.keycloak:keycloak-services:20.0.3")
Extracting the constant and keeping it pinned to the version we're targeting makes sense! Thanks, @bickelj.

2023-02-28 02:13 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        // mobileNumber of course has to be further validated on proper format, country code, ...
Yes, I agree that making a separate validation call during the same authentication workflow would not make sense! I still haven't had (and probably won't have) time to test this myself; what does happen when a user with an unparseable phone number attempts to log in?

You're right that entry-time validation is the thing to do. I've used [Google's libphonenumber](https://github.com/google/libphonenumber) before, and it appears to have Java bindings. That sounds out of scope for this PR, though; should we open a follow-up issue for that?

2023-02-28 02:49 UTC, jasonaowen approved these changes
This looks good! Thanks for the excellent follow-through, @bickelj.

After talking with @jim-mcgowan today, I believe we decided that my time was not best spent on testing this code - we can verify it works in [our testing environment](https://twitter.com/stahnma/status/634849376343429120).

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +                    + "` property in the LOGIN theme but lookup failed.", ioe);
Ooh, I like this! Very clear error message.

(Please mark as resolved once you've read!)

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +         } else {
I think it'll be more readable to do an early `return` out of this check, as we do out of the `code` null check immediately above, rather than an `else` block.

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/test/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticatorTest.java
> +                .thenReturn(Map.of(SENDER_ID_PROPERTY_NAME, "Testing"));
Nicely done figuring out these mocks!

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        if (now.isAfter(expiration)) {
This is way more readable!

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/.github/workflows/build.yml
> +      - main
The fact that you found it beneficial to specifically mention this branch during development suggests that we might be overly restrictive here. Maybe we should just run the build and tests on all branches?

```suggestion
on:
  push:
  pull_request:
```

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/.github/workflows/test.yml
> +      - main
Likewise:

```suggestion
on:
  push:
  pull_request:
```

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/.github/workflows/test.yml
> +        run: ./gradlew test jacocoReport
Hmm, I'm not seeing these checks running. Did this work as you expected?

2023-02-28 02:49 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/SmsSender.java
> +                    missingEnvVars);
Very nice!

2023-02-28 15:21 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        // mobileNumber of course has to be further validated on proper format, country code, ...
> what does happen when a user with an unparseable phone number attempts to log in?

I configured the test user with `mobile_number=bad&numb)er`, attempted the browser+sms flow, and got this error (good):
![when_a_bad_phone_number_is_configured_for_user_who_attempts_login_to_public_client](https://user-images.githubusercontent.com/8806433/221895977-d8498bf7-54f3-4355-b58e-a54583b4c6dc.png)

I further confirmed back on the client interface that the user was *not* authenticated despite the error.

> I've used [Google's libphonenumber](https://github.com/google/libphonenumber) before, and it appears to have Java bindings. That sounds out of scope for this PR, though; should we open a follow-up issue for that?

A separate issue sounds good to me. I created https://github.com/PhilanthropyDataCommons/auth/issues/5.

2023-02-28 15:24 UTC, bickelj commented on twilio-keycloak-provider/.github/workflows/build.yml
> +      - main
Good call.

2023-02-28 15:30 UTC, bickelj commented on twilio-keycloak-provider/.github/workflows/test.yml
> +        run: ./gradlew test jacocoReport
Nope. I think it is due to this being a (potentially) multi-project repository and I put the workflow in a subdirectory, not in the root directory. There is further awkwardness with the multi-component build inside the subdirectory. I didn't want to assume that every project in this repository would use the same `gradle` build system. The reason for the weird setup is that was the default setup on `gradle init`. In other words, expediency. A quick attempt to change the layout did not succeed at first so I continued with the default setup. Perhaps a new issue to revisit the project layout would be appropriate. Another unfortunate effect is the disconnection of the repository from its upstream repository, https://github.com/dasniko/keycloak-2fa-sms-authenticator. For this particular check, I'll move the workflow out to the root and see if that fixes it.

2023-02-28 15:40 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +         } else {
Fair enough and easy enough. But now I am reconsidering this interesting little block:

```java
else if (execution.isConditional() || execution.isAlternative()) {
    context.attempted();
}
```

This `context.attempted()` seems inconsistently applied. Is it something to worry about right now or can we leave it and punt to a separate issue?

2023-02-28 16:36 UTC, bickelj commented on twilio-keycloak-provider/.github/workflows/test.yml
> +        run: ./gradlew test jacocoReport
Somewhat fixed but the remainder can be improved in #4

2023-02-28 16:41 UTC, bickelj commented
I am still torn on all the squashing but that is a discussion for another day. Squashed and it looks like it's working. Merging.

2023-02-28 16:41 UTC, merged

2023-02-28 18:49 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +        // mobileNumber of course has to be further validated on proper format, country code, ...
Oh, that's great! Thanks, @bickelj.

2023-02-28 18:53 UTC, jasonaowen commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +         } else {
Good call out - I'm afraid I don't know enough about Keycloak authentication workflows to say one way or the other.

2023-02-28 19:00 UTC, bickelj commented on twilio-keycloak-provider/lib/src/main/java/org/philanthropydatacommons/auth/twilio/authenticator/SmsAuthenticator.java
> +         } else {
It's like this in the workflow configuration. Currently "required" but could be an alternative.
![authentication_flow_setup_required_vs_alternative_vs_disabled](https://user-images.githubusercontent.com/8806433/221952900-80394155-96cd-48c4-9f2d-aa4afb35e806.png)

2023-03-02 17:24 UTC, bickelj commented
@jasonaowen and @kfogel I have a question regarding process. Above I squashed, force pushed, and then presumed to merge before re-review. This was following a pattern established in the `service` project, but would it be better to have a reviewer actually click merge? Or to at least confirm the exact squashed commit has been re-reviewed prior to merge?

2023-03-02 23:13 UTC, jasonaowen commented
@bickelj and I talked about this a bit offline, but for the record: the way I like to work - and I believe the way @slifty likes to work - is for the author to merge PRs after getting an approving review. I like the way this spreads responsibility and autonomy, and it also gives reviewers the opportunity to leave "yes, and..." reviews with optional suggestions - as I did above - and leave it up to the author to take those suggestions or not as they see fit.

One side note is that we should clean up branches after they're merged; there's a [setting to do so automatically](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) for this that I'm following up about with the folks who can make that change. For now, I'll delete this one by hand.